services:

  frontend:
    build:
      context: frontend
      dockerfile: .Dockerfile
      args:
        VITE_ADMIN_USERNAME: admin
        VITE_ADMIN_PASSWORD: changeit
        VITE_API_URL: http://localhost:5001
    container_name: soad-fe
    environment:
      - TZ=Europe/Prague
    ports:
      - "5000:80"

  backend:
    build:
      context: backend
      dockerfile: .Dockerfile
    container_name: soad-be
    depends_on:
      - database
    environment:
      - TZ=Europe/Prague
      - DATABASE_URL=postgresql://api:changeit@database:5432/soad
      - SECRET=top_super_secret
      - GDRIVE_CREDENTIALS_DIR=./google_drive
      - OUTPUT_DIR=/data
      - AE_IP_ADDRESS=127.0.0.1
      - AE_PORT=40999
      - MSC_EXPOSURE_TIME=60
      - MOCK_DATA_DIR=/mock_data
      - MOCK_ACOUSTIC_EMISSION=True
      - MOCK_RGB_CAMERA=True
      - MOCK_MULTI_SPECTRAL_CAMERA=True
      - AUTH_USER=admin
      - AUTH_PASSWORD=changeit
    ports:
      - "5001:80"
    volumes:
      - files_volume:/soad

  database:
    image: postgres:17-alpine
    container_name: soad-db
    ports:
      - "5002:5432"
    environment:
      TZ: Europe/Prague
      PGDATA: /var/lib/postgresql/data/db-files/
      POSTGRES_DB: soad
      POSTGRES_USER: api
      POSTGRES_PASSWORD: changeit
    volumes:
      - database_volume:/var/lib/postgresql/data/

volumes:
  database_volume:
  files_volume: