services:

  frontend:
    build:
      context: frontend
      dockerfile: .Dockerfile
    container_name: soad-fe
    ports:
      - "5000:80"

  backend:
    build:
      context: backend
      dockerfile: .Dockerfile
    container_name: soad-be
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://api:changeit@database:5432/soad
      - SECRET=top_super_secret
    ports:
      - "5001:80"

  database:
    image: postgres:17-alpine
    container_name: soad-db
    ports:
      - "5002:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/db-files/
      POSTGRES_DB: soad
      POSTGRES_USER: api
      POSTGRES_PASSWORD: changeit
    volumes:
      - database_volume:/var/lib/postgresql/data/

volumes:
  database_volume: