name: Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt
        pip install pytest

#    - name: Run tests
#      run: pytest

    - name: Upload to Alwaysdata via SCP
      if: success()
      run: |
        ssh -o StrictHostKeyChecking=no prazdnyretezec:${{ secrets.ALWAYSDATA_PASSWORD }}@ssh-prazdnyretezec.alwaysdata.net 'rm -rf /home/prazdnyretezec/soad/backend/*'
        scp -o StrictHostKeyChecking=no -r ./backend prazdnyretezec:${{ secrets.ALWAYSDATA_PASSWORD }}@ssh-prazdnyretezec.alwaysdata.net:/home/prazdnyretezec/soad/backend
