name: Test & Deploy

on:
  push:
    branches:
      - main
#
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt
        pip install pytest

    #- name: Run tests
      #run: pytest

    - name: Upload to Alwaysdata via SCP and start backend
      if: success()
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ALWAYSDATA_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no prazdnyretezec@ssh-prazdnyretezec.alwaysdata.net 'rm -rf /home/prazdnyretezec/soad/backend/*'
        scp -o StrictHostKeyChecking=no -r ./backend prazdnyretezec@ssh-prazdnyretezec.alwaysdata.net:/home/prazdnyretezec/soad
        ssh -o StrictHostKeyChecking=no prazdnyretezec@ssh-prazdnyretezec.alwaysdata.net 'python -m venv /home/prazdnyretezec/soad/backend/.venv && source /home/prazdnyretezec/soad/backend/.venv/bin/activate && pip install -r /home/prazdnyretezec/soad/backend/requirements.txt'
        curl -i -X POST --basic --user "prazdnyretezec:${{ secrets.ALWAYSDATA_API_KEY }}" https://api.alwaysdata.com/v1/site/947386/restart
