name: Test & Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies & run tests
        working-directory: frontend
        run: |
          yarn install --frozen-lockfile
          yarn test

      - name: Build production bundle
        working-directory: frontend
        run: |
          yarn build

      - name: Prepare artifacts
        run: |
          mkdir -p deploy
          cp -R frontend/dist/* deploy/

      #- name: Deploy to server via SCP
      #  if: success()
      #  run: |
      #    ssh user@your-server.com "mkdir -p /var/www/app"
      #    scp -r deploy/* user@your-server.com:/var/www/app/
      #    ssh user@your-server.com "sudo systemctl restart your-frontend-service"
